### ISSUE TITLE
Monitor Running Tasks

### ISSUE THREAD

**Issue by cmenzi** [StephenCleary/AsyncDiagnostics#2]
Hi Stephen

Is there a way to montior running tasks without creating a custom scheduler? Because most of time I use Task.Run.

I tried to use something like this:
```
public static IReadOnlyCollection<Task> GetRunningTasks()
{
    TaskScheduler currentTaskScheduler = TaskScheduler.Current;
    // Reflection with Fasterflect to call the protected method
    List<Task> runningTasks = ((IEnumerable<Task>)currentTaskScheduler.CallMethod("GetScheduledTasks")).ToList();
    return runningTasks;
}
```
But this doesn't work. Then I found this solution, but this also may include the wrong information:

```
public static int GetWorkingThreads()
{
	int maxThreads;
	int completionPortThreads;
	ThreadPool.GetMaxThreads(out maxThreads, out completionPortThreads);

	int availableThreads;
	ThreadPool.GetAvailableThreads(out availableThreads, out completionPortThreads);

	return maxThreads - availableThreads;
}
```

Is there a way with your postsharp implementation to track this?

Why I need that. We have some SpecFlow tests (which have a static context) and some developers didn't correctly dispose some RX subscription and the current test means that everything is finished but after the teardown there is still a handler which gets hooked.

To prevent that I like to assert if there is still an active task.

I know: "Please program correctly" but there are developers which may forget a small dispose and didn't saw that there is still something runnning.

I think this could be the rigth repository for that? :-)

Thx Cédric

**Comment by StephenCleary** [comment]
No, sorry, `AsyncDiagnostics` only provides a caller stack for asynchronous code.

I'm not aware of any way to track running tasks unless you use a custom `TaskScheduler`/`SynchronizationContext`.
